### ISSUE TITLE
Suggestion: Multiple entries for fish detection

### ISSUE THREAD

**Issue by Jiroga** [yeeterlol/FishingPlus#2]
As far as I'm aware, the fish detection system only works with a single Fish ID, with the option to have it enabled or disabled through the toggle in-game. It would be great to allow multiple specific entries through some sort of array, or even use table categories such as "ocean" or "lake" to alert the player whenever they catch anything from that table, if at all possible.

Alternatively, an option to alert the player when they catch _anything_ would be more than welcome!

Thank you for the fantastic mod! :>

**Comment by yeeterlol** [comment]
added to 1.4
