### ISSUE TITLE
Version 1.4.0 is crashing the game.

### ISSUE THREAD

**Issue by giosqm** [yeeterlol/FishingPlus#3]
1.3.0 works fine with all the mods I'm using but for some reason 1.4.0 crashes the game upon launch.

![Captura de tela 2024-11-04 225342](https://github.com/user-attachments/assets/1ecac94d-ec8a-4686-a39f-d49204262020)

mod list

**Comment by yeeterlol** [comment]
bashfulbuckets is breaking the mod
