### ISSUE TITLE
Incompatibility with Bashful Buckets

### ISSUE THREAD

**Issue by SCAbruh** [yeeterlol/FishingPlus#4]
The current version of the mod (v1.4.0) causes a crash on startup when [Bashful Buckets](https://thunderstore.io/c/webfishing/p/DreamwalkerSisyphe/BashfulBuckets/) is installed. (Likely caused by the auto-collect from buckets feature?)

**Comment by yeeterlol** [comment]
yeah bashful buckets wrote slop code which broke my mod

**Comment by yeeterlol** [comment]
sent pr to her and she is not gonna update for a bit
