### ISSUE TITLE
Can't interact with the screen?

### ISSUE THREAD

**Issue by DvodUwU** [yeeterlol/FishingPlus#8]
The only thing I can interact with is the config for this mod in the top left corner. It's like the left mouse button were disabled for everything that isn't a different interface like inventory, pause menu and, well, the mods config screen. This also only happens when in a lobby and I am very sure that I'm using the newest version from few hours ago I believe. in addition to that- the zip file from the download contains more than just the mod which was rather confusing in the beginning. 
pls fix, kthxbye :D

**Comment by Kraftium** [comment]
Personally I can interact with the inventory and escape/settings menu fine, but in the game, I cannot interact with the top right buttons as well as the YAAM GUI just like you.

**Comment by yeeterlol** [comment]
fixed in 1.5.5 i hope
