### ISSUE TITLE
Mod Not Loading/Activating Correctly

### ISSUE THREAD

**Issue by EminentEmily** [yeeterlol/FishingPlus#9]
Hello:

I installed this mod and it appears not to be functioning. I ensured that the correct prerequisite (GDWeave) was installed, and tried that mod by itself to ensure there were no conflicts with other mods. If I have TackleBox enabled I can see settings for it, but they don't appear to be working. I tested the auto buddy catch and it's not working, and I see no other changes to the UI or whatnot.

**Comment by yeeterlol** [comment]
still broken?
